#!/usr/bin/env bash
# Write scripts/ci/remote-ollama.env (gitignored) for cloud/LAN bridge.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${REMOTE_OLLAMA_ENV:-$ROOT/scripts/ci/remote-ollama.env}"
MODEL="${OLLAMA_MODEL:-llama3.2}"
PORT="${OLLAMA_PORT:-11434}"

BASE_URL="${OLLAMA_BASE_URL:-}"
if [[ -z "$BASE_URL" ]]; then
  LAN_IP=""
  if command -v ipconfig >/dev/null 2>&1; then
    for iface in en0 en1; do
      LAN_IP="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
      [[ -n "$LAN_IP" ]] && break
    done
  fi
  if [[ -n "$LAN_IP" ]] && curl -sf --connect-timeout 2 "http://${LAN_IP}:${PORT}/api/tags" >/dev/null 2>&1; then
    BASE_URL="http://${LAN_IP}:${PORT}"
  elif command -v tailscale >/dev/null 2>&1; then
    TS="$(tailscale ip -4 2>/dev/null | head -1 || true)"
    if [[ -n "$TS" ]] && curl -sf --connect-timeout 2 "http://${TS}:${PORT}/api/tags" >/dev/null 2>&1; then
      BASE_URL="http://${TS}:${PORT}"
    fi
  fi
  if [[ -z "$BASE_URL" ]]; then
    echo "Could not auto-detect reachable Ollama URL."
    echo "Usage: OLLAMA_BASE_URL=http://192.168.x.x:11434 $0"
    exit 1
  fi
fi

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# Generated by scripts/ci/init_remote_ollama_env.sh — gitignored.
OLLAMA_BASE_URL=${BASE_URL}
OLLAMA_MODEL=${MODEL}
EOF
chmod 600 "$OUT" 2>/dev/null || true
echo "Wrote: $OUT"
cat "$OUT"
echo ""
echo "Test: $ROOT/scripts/ci/check_ollama_bridge.sh"
